# Generated by Django 5.2.8 on 2025-11-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the book title', max_length=200)),
                ('author', models.CharField(help_text="Enter the author's name", max_length=100)),
                ('published_date', models.DateField()),
                ('isbn_number', models.CharField(help_text='Enter the ISBN number', max_length=13)),
            ],
        ),
    ]
